create extension if not exists "pgcrypto";

create table if not exists stores (
  id uuid primary key default gen_random_uuid(), subdomain text unique not null, name text not null, owner_user_id uuid not null, stripe_account_id text, is_live boolean default false, status text not null default 'draft', platform_fee_percent numeric(5,2), logo_url text, accent_color text, tagline text, notification_email text, branding_configured boolean not null default false, shipping_flat_cents int not null default 0, free_shipping_threshold_cents int, shipping_configured boolean not null default false, contact_email text, contact_phone text, shipping_policy text, returns_policy text, privacy_policy text, terms_policy text, created_at timestamptz default now(),
  constraint stores_platform_fee_percent_range_check check (platform_fee_percent is null or (platform_fee_percent >= 0 and platform_fee_percent <= 100)), constraint stores_status_check check (status in ('draft','active','suspended','closed')), constraint stores_shipping_flat_cents_nonnegative_check check (shipping_flat_cents >= 0), constraint stores_free_shipping_threshold_positive_check check (free_shipping_threshold_cents is null or free_shipping_threshold_cents > 0)
);
create table if not exists platform_admins (user_id uuid primary key, created_at timestamptz default now());
create table if not exists products (id uuid primary key default gen_random_uuid(), store_id uuid not null references stores(id) on delete cascade, name text not null, price_cents int not null, image_url text, inventory int default 0, description text, category text, status text not null default 'draft', low_stock_alerted_at timestamptz, created_at timestamptz default now(), constraint products_price_cents_nonnegative_check check (price_cents >= 0), constraint products_inventory_nonnegative_check check (inventory >= 0), constraint products_status_check check (status in ('draft','active','archived')));
create table if not exists discounts (id uuid primary key default gen_random_uuid(), store_id uuid not null references stores(id) on delete cascade, code text not null, discount_type text not null, discount_value int not null, starts_at timestamptz, ends_at timestamptz, max_redemptions int, is_active boolean not null default true, created_at timestamptz not null default now(), constraint discounts_code_format_check check (code = upper(code) and code ~ '^[A-Z0-9_-]{3,32}$'), constraint discounts_type_check check (discount_type in ('percent','fixed')), constraint discounts_value_check check ((discount_type = 'percent' and discount_value between 1 and 100) or (discount_type = 'fixed' and discount_value > 0)), constraint discounts_window_check check (starts_at is null or ends_at is null or starts_at < ends_at), constraint discounts_max_redemptions_check check (max_redemptions is null or max_redemptions > 0), unique(store_id, code));
create table if not exists orders (
  id uuid primary key default gen_random_uuid(), store_id uuid not null references stores(id) on delete cascade, public_token uuid not null unique default gen_random_uuid(), customer_email text not null, subtotal_cents int not null, discount_id uuid references discounts(id) on delete set null, discount_code text, discount_type text, discount_value int, discount_cents int not null default 0, shipping_cents int not null default 0, total_cents int not null, status text default 'pending', stripe_payment_intent_id text, platform_fee_percent_snapshot numeric(5,2), platform_fee_cents int, paid_at timestamptz, line_items jsonb not null default '[]'::jsonb, shipping_address jsonb not null default '{}'::jsonb, tracking_number text, carrier text, inventory_reserved boolean not null default false, refunded_amount_cents int not null default 0, has_shipped boolean not null default false, created_at timestamptz default now(),
  constraint orders_total_cents_nonnegative_check check (total_cents >= 0), constraint orders_subtotal_cents_nonnegative_check check (subtotal_cents >= 0), constraint orders_discount_cents_range_check check (discount_cents >= 0 and discount_cents <= subtotal_cents), constraint orders_discount_snapshot_consistency_check check ((discount_id is null and discount_code is null and discount_type is null and discount_value is null and discount_cents = 0) or (discount_code is not null and discount_type in ('percent','fixed') and discount_value is not null and discount_value > 0 and discount_cents >= 0)), constraint orders_shipping_cents_nonnegative_check check (shipping_cents >= 0), constraint orders_total_matches_components_check check (total_cents = subtotal_cents - discount_cents + shipping_cents), constraint orders_refunded_amount_nonnegative_check check (refunded_amount_cents >= 0), constraint orders_refunded_amount_not_over_total_check check (refunded_amount_cents <= total_cents), constraint orders_status_check check (status in ('pending','paid','shipped','delivered','expired','partially_refunded','refunded')), constraint orders_carrier_check check (carrier is null or carrier in ('aramex','emirates_post','other')), constraint orders_platform_fee_percent_snapshot_range_check check (platform_fee_percent_snapshot is null or (platform_fee_percent_snapshot >= 0 and platform_fee_percent_snapshot <= 100)), constraint orders_platform_fee_cents_range_check check (platform_fee_cents is null or (platform_fee_cents >= 0 and platform_fee_cents <= total_cents)), constraint orders_platform_fee_snapshot_pair_check check ((platform_fee_percent_snapshot is null) = (platform_fee_cents is null))
);
create table if not exists discount_redemptions (id uuid primary key default gen_random_uuid(), discount_id uuid not null references discounts(id) on delete cascade, store_id uuid not null references stores(id) on delete cascade, order_id uuid not null unique references orders(id) on delete cascade, status text not null default 'reserved', created_at timestamptz not null default now(), redeemed_at timestamptz, constraint discount_redemptions_status_check check (status in ('reserved','redeemed','released')));
create table if not exists audit_log (id uuid primary key default gen_random_uuid(), store_id uuid references stores(id) on delete cascade, actor_user_id uuid not null, actor_role text not null, action text not null, target_type text, target_id text, metadata jsonb not null default '{}'::jsonb, created_at timestamptz default now(), constraint audit_log_actor_role_check check (actor_role in ('merchant','platform_admin')));
create table if not exists webhook_events (
  id uuid primary key default gen_random_uuid(), provider text not null, event_id text not null, event_type text not null, payload jsonb not null default '{}'::jsonb, status text not null default 'received', attempt_count int not null default 1, error text, received_at timestamptz not null default now(), processing_started_at timestamptz, processed_at timestamptz, unique (provider, event_id),
  constraint webhook_events_provider_check check (provider in ('stripe','aftership')), constraint webhook_events_status_check check (status in ('received','processing','processed','failed')), constraint webhook_events_attempt_count_positive_check check (attempt_count >= 1), constraint webhook_events_processing_lease_check check ((status = 'processing') = (processing_started_at is not null))
);
create table if not exists email_outbox (
  id uuid primary key default gen_random_uuid(), dedupe_key text not null unique, store_id uuid references stores(id) on delete cascade, order_id uuid references orders(id) on delete cascade, kind text not null, recipient text not null, subject text not null, html text not null, status text not null default 'pending', attempt_count int not null default 0, next_attempt_at timestamptz not null default now(), processing_started_at timestamptz, last_error text, provider_message_id text, created_at timestamptz not null default now(), sent_at timestamptz,
  constraint email_outbox_status_check check (status in ('pending','processing','failed','sent')), constraint email_outbox_attempt_count_nonnegative_check check (attempt_count >= 0), constraint email_outbox_processing_lease_check check ((status = 'processing') = (processing_started_at is not null)), constraint email_outbox_sent_at_check check ((status = 'sent') = (sent_at is not null))
);
create table if not exists rate_limits (scope text not null, subject text not null, window_start timestamptz not null, request_count integer not null default 1 check (request_count > 0), primary key (scope, subject, window_start));
create index if not exists idx_products_store on products(store_id); create index if not exists idx_products_store_status on products(store_id, status); create index if not exists idx_discounts_store_active on discounts(store_id, is_active, code); create index if not exists idx_discount_redemptions_discount_status on discount_redemptions(discount_id, status); create index if not exists idx_orders_store on orders(store_id); create index if not exists idx_orders_store_paid_at on orders(store_id, paid_at desc) where paid_at is not null; create index if not exists idx_orders_paid_at on orders(paid_at desc) where paid_at is not null; create index if not exists idx_stores_subdomain on stores(subdomain); create index if not exists idx_stores_status on stores(status); create index if not exists idx_audit_log_store on audit_log(store_id); create index if not exists idx_webhook_events_status_received on webhook_events(status, received_at); create index if not exists idx_webhook_events_processing_lease on webhook_events(processing_started_at) where status = 'processing'; create index if not exists idx_email_outbox_due on email_outbox(status, next_attempt_at) where status in ('pending','failed','processing'); create index if not exists idx_rate_limits_window_start on rate_limits(window_start);
